const ACTIVE_PAD_INDEX = 'ACTIVE_PAD_INDEX';
const PAD_ON = 'PAD_ON';
const PAD_OFF = 'PAD_OFF';
const NOTE_ON = 'NOTE_ON';
const NOTE_OFF = 'NOTE_OFF';
const SEQUENCE_PLAY = 'SEQUENCE_PLAY';
const SEQUENCE_STARTED = 'SEQUENCE_STARTED';
const SEQUENCE_ENDED = 'SEQUENCE_ENDED';
const FAILED_ATTEMPT = 'FAILED_ATTEMPT';
const SUCCESSFUL_ATTEMPT = 'SUCCESSFUL_ATTEMPT';

export {
  ACTIVE_PAD_INDEX,
  PAD_ON, 
  PAD_OFF,
  SEQUENCE_STARTED,
  SEQUENCE_ENDED,
  SEQUENCE_PLAY,
  SUCCESSFUL_ATTEMPT,
  FAILED_ATTEMPT,
  NOTE_ON,
  NOTE_OFF,
};
