const ACTIVE_PAD_INDEX = 'ACTIVE_PAD_INDEX';
const PAD_ON = 'PAD_ON';
const PAD_OFF = 'PAD_OFF';
const SEQUENCER_PLAY = 'SEQUENCER_PLAY';
const SEQUENCER_CUE = 'SEQUENCER_CUE';
const SEQUENCE_STARTED = 'SEQUENCE_STARTED';
const SEQUENCE_ENDED = 'SEQUENCE_ENDED';

export {
  ACTIVE_PAD_INDEX,
  PAD_ON, 
  PAD_OFF,
  SEQUENCE_STARTED,
  SEQUENCE_ENDED,
  SEQUENCER_CUE, 
  SEQUENCER_PLAY,
};
